services:
  mongodb:
    image: mongo:6.0
    container_name: kahoot-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: kahoot_clone
    volumes:
      - mongodb_data:/data/db
    networks:
      - kahoot-network

  redis:
    image: redis
    ports:
      - "6379:6379"
  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: "redis://redis:6379"
    networks:
      - kahoot-network
    depends_on:
      - redis

volumes:
  mongodb_data:
  redis_data:

networks:
  kahoot-network:
    driver: bridge
